// Moved from src/decapod/lib.rs
use super::maintain_generated_dockerfile_contract;

#[test]
fn generated_dockerfile_heal_deduplicates_version_arg() {
    let current = "\
# Generated by decapod container profile
# Path: .decapod/managed/Dockerfile
ARG DECAPOD_IMAGE=ghcr.io/decapodlabs/decapod:v0.62.2
FROM $DECAPOD_IMAGE
ARG DECAPOD_VERSION=0.62.2
ARG DECAPOD_VERSION=0.62.2
RUN echo project layer
";
    let expected = "\
# Generated by decapod container profile
# Path: .decapod/managed/Dockerfile
ARG DECAPOD_IMAGE=ghcr.io/decapodlabs/decapod:v0.62.3
FROM $DECAPOD_IMAGE
ARG DECAPOD_VERSION=0.62.3
";

    let updated = maintain_generated_dockerfile_contract(current, expected)
        .expect("dockerfile should be healed");
    assert!(updated.contains("ARG DECAPOD_IMAGE=ghcr.io/decapodlabs/decapod:v0.62.3"));
    assert_eq!(
        updated
            .lines()
            .filter(|line| line.starts_with("ARG DECAPOD_VERSION="))
            .count(),
        1
    );
    assert!(updated.contains("ARG DECAPOD_VERSION=0.62.3"));
    assert!(updated.contains("RUN echo project layer"));
}
